### ISSUE TITLE
TODO ahead

### ISSUE THREAD

**Issue by dbzkunalss** [sudodevs-inc/rait_sync#1]
- [x] fcm functions

- [x] signup check requests

- [x] ensure typesafety of response

- [x] responsive screens with dynamic widget tree
